package com.api.prices.crypto.cryptoprices.entity;

public enum BinanceCurrency {


    BCH, ETH, XRP, DASH, ETC, BNB, EOS, BTG, LTC, LINK, ICX, XMR, ADA,
    ZEC, AION, BCD, ATOM, XTZ, WAVES, XLM, MATIC, RVN, TRX, NEO, INS,
    FET, PERL, BAT, ENJ, TROY, OAX, REP, WAN, ONT, FTT, VET, ARN, MTL,
    ALGO, TOMO, QTUM, HBAR, IOTA, WTC, VIB, THETA, MDA, MITH, RCN, LEND,
    ZRX, GO, LSK, XEM, PPT, OMG, BAND, FTM, XZC, KNC, TNT, CHZ, OGN, AGI,
    DOCK, TCT, CELR, ONE, RLC, NKN, KAVA, WABI, ERD, BQX, NANO, REN, GNT,
    HC, ZIL, STEEM, DATA, LOOM, BEAM, TFUEL, ARPA, MANA, SKY, KMD, MFT, AMB,
    LUN, ZEN, COS, GAS, DOGE, EVX, LRC, DREP, POWR, BNT, DGD, POLY, IOST, CVC,
    XVG, DUSK, STRAT, FUEL, NULS, ELF, BCPT, PIVX, HOT, GRS, PHB, MTH, SNM, BLZ,
    STX, DCR, CMT, MCO, QKC, ENG, AE, DLT, SNT, GTO, NEBL, EDO, OST, KEY, GVT,
    NAS, SYS, GXS, ANKR, VIA, CND, APPC, QSP, ARK, CDT, STORJ, VITE, POE, CTXC,
    VIBE, REQ, AST, NXS, BTS, POA, WPR, NCASH, ARDR, ONG, BRD, TNB, QLC, IOTX,
    RDN, FUN, NAV, SC, DNT, STORM, YOYO, ADX, SNGLS, COCOS


}
